language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build ionoscloud.gemspec
  - gem install ./ionoscloud-6.0.0.beta.4.gem
