=begin
#CLOUD API

#IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.

The version of the OpenAPI document: 6.0-SDK.3

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Ionoscloud::ContractResourcesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ContractResourcesApi' do
  before do
    # run before each test
    @api_instance = Ionoscloud::ContractResourcesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ContractResourcesApi' do
    it 'should create an instance of ContractResourcesApi' do
      expect(@api_instance).to be_instance_of(Ionoscloud::ContractResourcesApi)
    end
  end

  # unit tests for contracts_get
  # Retrieve a Contract
  # Retrieves the attributes of user&#39;s contract. In this version, the resource became a collection.
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :pretty Controls whether the response is pretty-printed (with indentations and new lines).
  # @option opts [Integer] :depth Controls the detail depth of the response objects.  GET /datacenters/[ID]  - depth&#x3D;0: Only direct properties are included; children (servers and other elements) are not included.  - depth&#x3D;1: Direct properties and children references are included.  - depth&#x3D;2: Direct properties and children properties are included.  - depth&#x3D;3: Direct properties and children properties and children&#39;s children are included.  - depth&#x3D;... and so on
  # @option opts [Integer] :x_contract_number Users with multiple contracts must provide the contract number, against which all API requests are to be executed.
  # @return [Contracts]
  describe 'contracts_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
